export const elements = {
    TEXTBOX: 'TEXTBOX',
    SLIDER: 'SLIDER',
    TITLE: 'TITLE',
    DROPDOWN: 'DROPDOWN',
    GRID_LAYOUT_3_3: 'GRID_LAYOUT_3_3',
    GRID_LAYOUT_1_2: 'GRID_LAYOUT_1_2',
    GRID_LAYOUT: 'GRID_LAYOUT',
    GRID_COL: 'GRID_COL',
    CAROUSEL: 'CAROUSEL',
};